### ISSUE TITLE
As a user, I should be able to log into the application

### ISSUE THREAD

**Issue by Musigwa-zz** [Musigwa-zz/SpAllocBE#13]
### Is your feature request related to a problem?

> Please describe how they related and give a clear and concise description of what the problem is. 
> Ex. I'm always frustrated when [...]

#### :sparkles: Describe the solution you'd like :sparkles

> A clear and concise description of what you want to happen.

#### :part_alternation_mark: Describe alternatives you've considered :part_alternation_mark

> A clear and concise description of any alternative solutions or features you've considered.

#### Additional context

> Add any other context or screenshots about the feature request here.

#### Checklist of acceptance criteria

- [ ] This should be tested and working fine
- [ ] This should be tested and working fine
- [ ] This should be tested and working fine
- [ ] This should be tested and working fine
