### ISSUE TITLE
Users should be able to view, book and organise their workstations

### ISSUE THREAD

**Issue by Musigwa-zz** [Musigwa-zz/SpAllocBE#19]
### Is your feature request related to a problem?

> Users should view, book and manage their workstation during the period they have booked them

#### :sparkles: Describe the solution you'd like :sparkles

> As a user, I need to get a `list` of workstations, `check` each one of them, be able to `book` and be able to manage my workspace with its related tools.
 
#### :part_alternation_mark: Describe alternatives you've considered :part_alternation_mark

> None

#### Additional context

> None

#### Checklist of acceptance criteria

- [ ] A user should be able to book the available stations
- [ ] User should view the available spots
- [ ] User should view the details of each workstation
- [ ] User should be able to manage their stations
